/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author DavidSJ
 */
public class Vista extends javax.swing.JFrame {
    private Controlador controlador;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTF_Variable = new javax.swing.JTextField();
        JTF_TamanoVariable = new javax.swing.JTextField();
        JB_IngresarVariable = new javax.swing.JButton();
        JB_AgregarAmbitos = new javax.swing.JButton();
        JL_MostrarMensajeVariable = new javax.swing.JLabel();
        JL_MostrarMensajeTamano = new javax.swing.JLabel();
        JB_EliminarAmbito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Mostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTF_Variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_VariableActionPerformed(evt);
            }
        });

        JTF_TamanoVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_TamanoVariableActionPerformed(evt);
            }
        });

        JB_IngresarVariable.setText("Ingresar Variable");
        JB_IngresarVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_IngresarVariableActionPerformed(evt);
            }
        });

        JB_AgregarAmbitos.setText("Entrar Al Ambito");
        JB_AgregarAmbitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AgregarAmbitosActionPerformed(evt);
            }
        });

        JL_MostrarMensajeVariable.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        JL_MostrarMensajeVariable.setText("Ingresar Variable:");
        JL_MostrarMensajeVariable.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JL_MostrarMensajeVariable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JL_MostrarMensajeTamano.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        JL_MostrarMensajeTamano.setText("Ingresar Tamaño De La Variable:");
        JL_MostrarMensajeTamano.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JL_MostrarMensajeTamano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JB_EliminarAmbito.setText("Limpiar Memoria");
        JB_EliminarAmbito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminarAmbitoActionPerformed(evt);
            }
        });

        JL_Mostrar.setColumns(20);
        JL_Mostrar.setRows(5);
        jScrollPane1.setViewportView(JL_Mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_MostrarMensajeVariable)
                                .addGap(18, 18, 18)
                                .addComponent(JTF_Variable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JB_IngresarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB_AgregarAmbitos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(JB_EliminarAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(JL_MostrarMensajeTamano)
                                .addGap(40, 40, 40)
                                .addComponent(JTF_TamanoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_MostrarMensajeVariable)
                    .addComponent(JTF_Variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_MostrarMensajeTamano)
                    .addComponent(JTF_TamanoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_IngresarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_AgregarAmbitos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_EliminarAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_VariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_VariableActionPerformed

    }//GEN-LAST:event_JTF_VariableActionPerformed

    private void JTF_TamanoVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_TamanoVariableActionPerformed

    }//GEN-LAST:event_JTF_TamanoVariableActionPerformed

    private void JB_IngresarVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_IngresarVariableActionPerformed
        String nombreVariable = JTF_Variable.getText();
        int tamaño = Integer.parseInt(JTF_TamanoVariable.getText());
        controlador.ingresarVariable(nombreVariable, tamaño);
    }//GEN-LAST:event_JB_IngresarVariableActionPerformed

    private void JB_AgregarAmbitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AgregarAmbitosActionPerformed
        controlador.entrarAlAmbito();
    }//GEN-LAST:event_JB_AgregarAmbitosActionPerformed

    private void JB_EliminarAmbitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminarAmbitoActionPerformed
        controlador.limpiarMemoria();
    }//GEN-LAST:event_JB_EliminarAmbitoActionPerformed
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void mostrarMensajeVariable(String mensaje) {
        String textoActual = JL_Mostrar.getText();
        String nuevoTexto = textoActual.isEmpty() ? mensaje : textoActual + "\n" + mensaje;
        JL_Mostrar.setText(nuevoTexto);
    }

    public void mostrarVariables(String variables) {
        String textoActual = JL_Mostrar.getText();
        String nuevoTexto = textoActual.isEmpty() ? variables : textoActual + "\n" + variables;
        JL_Mostrar.setText(nuevoTexto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_AgregarAmbitos;
    private javax.swing.JButton JB_EliminarAmbito;
    private javax.swing.JButton JB_IngresarVariable;
    private javax.swing.JTextArea JL_Mostrar;
    private javax.swing.JLabel JL_MostrarMensajeTamano;
    private javax.swing.JLabel JL_MostrarMensajeVariable;
    private javax.swing.JTextField JTF_TamanoVariable;
    private javax.swing.JTextField JTF_Variable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
